---- MODULE PaperFeeKernel ----
EXTENDS Integers

\* GENERATED by scripts/10_generate_paper_fee_kernel_tla.py.
\* Do not hand-edit: the Python drift test binds this module to FeeEvent output.

NormalClearAligned == 200
NormalClearMinority == -200
NormalNoMajority == 200

AppealClearAligned == 200
AppealClearMinority == -200
AppealNoMajority == 200

OriginalVindicated == 200
OriginalOther == 0
OriginalNoMajority == 0

ClearMajorityPreservationSpread == 400
NoMajorityPreservationSpread == 0
ClearReversalCorrectionSpread == 200
NoMajorityCorrectionSpread == 0

AppealRewardNumerator == 5
AppealRewardDenominator == 2

CertifiedNormalProfiles == 21
CertifiedAppealProfiles == 156
EndToEndAppealProfiles == 150
AmbiguousAllTimeoutProfiles == 6
ConfiguredRungBoundaryCases == 18

FeeKernelWellFormed ==
    /\ ClearMajorityPreservationSpread =
           NormalClearAligned - NormalClearMinority
    /\ NoMajorityPreservationSpread = 0
    /\ ClearReversalCorrectionSpread =
           OriginalVindicated - OriginalOther
    /\ NoMajorityCorrectionSpread =
           OriginalNoMajority - OriginalOther
    /\ AppealRewardNumerator = 5
    /\ AppealRewardDenominator = 2
    /\ CertifiedNormalProfiles = 21
    /\ CertifiedAppealProfiles =
           EndToEndAppealProfiles + AmbiguousAllTimeoutProfiles

====
