"""Render the executable payoff certificate as an exact TLA+ module."""

from fractions import Fraction

from src.fee_simulator.analysis.paper_property_sweep import (
    PaperPropertySweepReport,
)


def render_paper_fee_kernel_tla(
    report: PaperPropertySweepReport,
) -> str:
    """Return a deterministic, integer-only TLA+ projection of ``report``."""

    payoff = report.payoff_kernel
    margins = report.paper_margins
    appeal_multiple = Fraction(str(report.appeal_reward_multiple))

    return f"""---- MODULE PaperFeeKernel ----
EXTENDS Integers

\\* GENERATED by scripts/10_generate_paper_fee_kernel_tla.py.
\\* Do not hand-edit: the Python drift test binds this module to FeeEvent output.

NormalClearAligned == {payoff["normal_clear_aligned"]}
NormalClearMinority == {payoff["normal_clear_minority"]}
NormalNoMajority == {payoff["normal_no_majority"]}

AppealClearAligned == {payoff["appeal_clear_aligned"]}
AppealClearMinority == {payoff["appeal_clear_minority"]}
AppealNoMajority == {payoff["appeal_no_majority"]}

OriginalVindicated == {payoff["original_vindicated"]}
OriginalOther == {payoff["original_other"]}
OriginalNoMajority == {payoff["original_no_majority"]}

ClearMajorityPreservationSpread == {margins["clear_majority_preservation_spread"]}
NoMajorityPreservationSpread == {margins["no_majority_preservation_spread"]}
ClearReversalCorrectionSpread == {margins["clear_reversal_correction_spread"]}
NoMajorityCorrectionSpread == {margins["no_majority_correction_spread"]}

AppealRewardNumerator == {appeal_multiple.numerator}
AppealRewardDenominator == {appeal_multiple.denominator}

CertifiedNormalProfiles == {report.normal_profiles_checked}
CertifiedAppealProfiles == {report.successful_appeal_profiles_checked}
EndToEndAppealProfiles == {report.end_to_end_appeal_profiles_checked}
AmbiguousAllTimeoutProfiles == {report.live_label_ambiguities_detected}
ConfiguredRungBoundaryCases == {report.configured_rung_boundary_cases_checked}

FeeKernelWellFormed ==
    /\\ ClearMajorityPreservationSpread =
           NormalClearAligned - NormalClearMinority
    /\\ NoMajorityPreservationSpread = 0
    /\\ ClearReversalCorrectionSpread =
           OriginalVindicated - OriginalOther
    /\\ NoMajorityCorrectionSpread =
           OriginalNoMajority - OriginalOther
    /\\ AppealRewardNumerator = 5
    /\\ AppealRewardDenominator = 2
    /\\ CertifiedNormalProfiles = 21
    /\\ CertifiedAppealProfiles =
           EndToEndAppealProfiles + AmbiguousAllTimeoutProfiles

====
"""
